> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# Some Interesting Torch Functions

An short introduction about PyTorch and about the chosen functions. 

- torch.rand
- torch.full
- torch.take
- torch.unbind
- torch.linspace

Before we begin, let's install and import PyTorch

In [18]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [19]:
# Import torch and other required modules
import torch

## Function 1 - TORCH.RAND

torch.rand(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)[0,1)

The shape of the tensor is defined by the variable argument size.

In [20]:
# Example 1 - working (change this)
>>> torch.rand(4)


tensor([7.1481e-02, 4.4614e-01, 3.4332e-04, 8.4891e-01])

Explanation about example

In [23]:
# Example 2 - working
torch.rand(2, 3)

tensor([[0.3850, 0.8198, 0.5549],
        [0.4637, 0.8893, 0.0723]])

Explanation about example

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
torch.rand[2, 3]

TypeError: ignored

Explanation about example

Closing comments about when to use this function

Let's save our work using Jovian before continuing.

In [14]:
!pip install jovian --upgrade --quiet

In [15]:
import jovian

In [16]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirbansaha/01-tensor-operations


'https://jovian.ai/anirbansaha/01-tensor-operations'

## Function 2 -  torch.full
`torch.full` returns a tensor of size size with the values filled with `fill_value`
The size can be a list or a tuple.






In [25]:
# Example 1 - working
torch.full(size=(3,2), fill_value=10)

tensor([[10, 10],
        [10, 10],
        [10, 10]])

Explanation about example

In [26]:
# Example 2 - working
torch.full(size=[2, 3, 4], fill_value=5)

tensor([[[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]],

        [[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]]])

Explanation about example

In [28]:
# Example 3 - breaking (to illustrate when it breaks)
torch.full(size=[2, 3, 4], fill_value=[5,2])

TypeError: ignored

Explanation about example

Closing comments about when to use this function

In [29]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirbansaha/01-tensor-operations


'https://jovian.ai/anirbansaha/01-tensor-operations'

## Function 3 - torch.take
`torch.take` returns a tensor with the elements of the input tensors at the given indices. The input tensor is treated as a 1D tensor to return the values.



In [30]:
# Example 1 - working
# 1D input Tensor
b = torch.tensor([24, 26, 55, 78, 10])
torch.take(b, torch.tensor([2]))

tensor([55])

Explanation about example

In [32]:
# Example 2 - working
# 2D input tensor
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.take(a, torch.tensor([3,4]))

tensor([4, 5])

Explanation about example

In [35]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.take(a, torch.tensor(3,1))

TypeError: ignored

Explanation about example

Closing comments about when to use this function

In [36]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirbansaha/01-tensor-operations


'https://jovian.ai/anirbansaha/01-tensor-operations'

## Function 4 - torch.unbind

`torch.unbind` removes a tensor dimension along the given dimension dim
The default dimension is 0 i.e. dim=0

In [37]:
# Example 1 - working
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.unbind(a)

(tensor([1, 2, 3]), tensor([4, 5, 6]))

Explanation about example

In [38]:
# Example 2 - working
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.unbind(a, dim=1)

(tensor([1, 4]), tensor([2, 5]), tensor([3, 6]))

Explanation about example

In [39]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.unbind(a, dim=2)

IndexError: ignored

Explanation about example

Closing comments about when to use this function

In [40]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirbansaha/01-tensor-operations


'https://jovian.ai/anirbansaha/01-tensor-operations'

## Function 5 - torch.linspace

`torch.linspace` is used to create a 1D equally spaced tensor between the values start and end . We can specify the size of the tensor with the steps parameters. The default is steps=100

In [46]:
# Example 1 - working
torch.linspace(1, 50)

tensor([ 1.0000,  1.4949,  1.9899,  2.4848,  2.9798,  3.4747,  3.9697,  4.4646,
         4.9596,  5.4545,  5.9495,  6.4444,  6.9394,  7.4343,  7.9293,  8.4242,
         8.9192,  9.4141,  9.9091, 10.4040, 10.8990, 11.3939, 11.8889, 12.3838,
        12.8788, 13.3737, 13.8687, 14.3636, 14.8586, 15.3535, 15.8485, 16.3434,
        16.8384, 17.3333, 17.8283, 18.3232, 18.8182, 19.3131, 19.8081, 20.3030,
        20.7980, 21.2929, 21.7879, 22.2828, 22.7778, 23.2727, 23.7677, 24.2626,
        24.7576, 25.2525, 25.7475, 26.2424, 26.7374, 27.2323, 27.7273, 28.2222,
        28.7172, 29.2121, 29.7071, 30.2020, 30.6970, 31.1919, 31.6869, 32.1818,
        32.6768, 33.1717, 33.6667, 34.1616, 34.6566, 35.1515, 35.6465, 36.1414,
        36.6364, 37.1313, 37.6263, 38.1212, 38.6162, 39.1111, 39.6061, 40.1010,
        40.5960, 41.0909, 41.5859, 42.0808, 42.5758, 43.0707, 43.5657, 44.0606,
        44.5556, 45.0505, 45.5455, 46.0404, 46.5354, 47.0303, 47.5253, 48.0202,
        48.5152, 49.0101, 49.5051, 50.00

Explanation about example

In [ ]:
# Example 2 - working
torch.linspace(start=1, end=50, steps=10)

Explanation about example

In [45]:
# Example 3 - breaking (to illustrate when it breaks)
torch.linspace[start=10, end=15, steps=22]

tensor([])

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion

In this assignment, we saw the working of Five functions available in PyTorch. There are a number of other useful functions. You can refer to the official documentation for the complete list of available functions.



## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html


In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
