# Numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5]) # rank 1 array
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(5,)


In [5]:
print(a[0], a[1])

1 2


In [6]:
a[0] = 11
print(a)

[11  2  3  4  5]


In [7]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
print(b[1,2])

6


In [13]:
arr1 = np.zeros((5,5))
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
arr2 = np.ones((5,5))
print(arr2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
arr3 = np.full((5,5), 9)
print(arr3)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [18]:
arr4 = np.eye(5)
print(arr4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
arr5 = np.random.random((5,5))
print(arr5)
                        

[[0.59834038 0.44273293 0.03428188 0.74524859 0.83505604]
 [0.16841737 0.72446466 0.33512771 0.03654017 0.72094496]
 [0.32675852 0.56439378 0.7654096  0.0590185  0.26389021]
 [0.28628912 0.15511583 0.39288023 0.05468016 0.11959823]
 [0.97599933 0.60174601 0.80840621 0.68984461 0.93978655]]
