> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Five awsome Numpy Function



Here some useful numpy function. 

- np.array_split()
- np.where()
- np.sort()
- np.prod()
- np.diff()

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [2]:
!pip install jovian --upgrade -q

In [3]:
import jovian

In [4]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirbansaha/numpy-array-operations


'https://jovian.ai/anirbansaha/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [6]:
# List of functions explained 
function1 = np.array_split
function2 = np.where
function3 = np.sort
function4 = np.prod
function5 = np.diff

## Function 1 - np.array_split

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [7]:
# Example 1 - working 
arr1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr2 = np.array_split(arr1, 3)
print(arr2)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In this example we split arr1 in 3 part


In [8]:
# Example 2 - working
arr3 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

arr4 = np.array_split(arr3, 3)

print(arr4)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


here, arr3 is a 2D array and we split them in three part


In [9]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr2 = np.split(arr1, 10)
print(arr2)

AttributeError: ignored

If we only use split then we have an error


In [10]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirbansaha/numpy-array-operations


'https://jovian.ai/anirbansaha/numpy-array-operations'

## Function 2 - where()

To search an array, use the `where()` method.

In [13]:
# Example 1 - working
arr6 = np.array([1, 2, 3, 4, 5, 4, 4])

arr7 = np.where(arr6 == 4)

print(arr7)

(array([3, 5, 6]),)


The example above will return a tuple: (array([3, 5, 6],)

Which means that the value 4 is present at index 3, 5, and 6.

In [15]:
# Example 2 - working
arr8 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr9 = np.where(arr8 % 2 == 0)

print(arr9)

(array([1, 3, 5, 7]),)


This example is search only the even number from the array

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
arr10 = np.array([1, 2, 3, 4, 5, 4, 4])

arr11 = np.where(arr10 = 4)

print(arr11)

TypeError: ignored

If i use only `=` then the program gives me error

This function is mainly ues for searching from a list

In [22]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirbansaha/numpy-array-operations


'https://jovian.ai/anirbansaha/numpy-array-operations'

## Function 3 - np.sort()

The NumPy ndarray object has a function called `sort()`, that will sort a specified array.

In [23]:
# Example 1 - working
arr12 = np.array([3, 2, 0, 1])

print(np.sort(arr12))

[0 1 2 3]


This `sort()` function sort the eliment of an array.

In [24]:
# Example 2 - working
arr13 = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr13))


[[2 3 4]
 [0 1 5]]


this function also works in 2D array.

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
arr14 = np.array([[3, 2, 4, a], [5, 0, 1]])

print(np.sort(arr14))


NameError: ignored

This function isn't work when two kind of data type in the same array.

This function will be helpful when we need to sort from a datasets.

In [26]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirbansaha/numpy-array-operations


'https://jovian.ai/anirbansaha/numpy-array-operations'

## Function 4 - np.prod()

To find the product of the elements in an array, use the `prod()` function.

In [27]:
# Example 1 - working
arr15= np.array([1, 2, 3, 4])

x = np.prod(arr15)

print(x)

24


`24` because 1\*2\*3\*4 = 24 

In [28]:
# Example 2 - working
import numpy as np

arr16 = np.array([1, 2, 3, 4])
arr17 = np.array([5, 6, 7, 8])

newarr = np.prod([arr16, arr17], axis=1)

print(newarr)

[  24 1680]


If I specify `axis=1`, NumPy will return the product of each array.

In [31]:
# Example 3 - breaking (to illustrate when it breaks)
arr18= np.array([1, 2, 3, 4],[7,9,6,5])

x = np.prod(arr18)

print(x)

TypeError: ignored

It isn't work in 2D array

This is very useful function

In [32]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirbansaha/numpy-array-operations


'https://jovian.ai/anirbansaha/numpy-array-operations'

## Function 5 - np.diff()

To find the discrete difference, use the diff() function.

In [33]:
# Example 1 - working
arr19 = np.array([10, 15, 25, 5])

newarr = np.diff(arr19)

print(newarr)

[  5  10 -20]


It is give the diffarance betwwen two eliments.

Here,
15-10=5, 25-15=10, and 5-25=-20

In [34]:
# Example 2 - working
arr20 = np.array([10, 15, 25, 5])

newarr = np.diff(arr20, n=2)

print(newarr)

[  5 -30]


 because: 15-10=5, 25-15=10, and 5-25=-20 AND 10-5=5 and -20-10=-30
 

In [41]:
# Example 3 - breaking (to illustrate when it breaks)
arr21 = np.array([10, 15, 25, 5],[5,5])

newarr = np.diff(arr21, n=0)

print(newarr)

TypeError: ignored

It is not work in 2d array

This is a usefull function


In [42]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anirbansaha/numpy-array-operations


'https://jovian.ai/anirbansaha/numpy-array-operations'

## Conclusion

This funtions are very useful function. When we are workin with a data sets then we need many kind of numpy function. Numpy funtion makes our codeing experience efficeint>

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'